name: Selenium with jUnit - CI

on:
  push:
    branches: [ "CheckPullRest" ]
  pull_request:
    branches: [ "CheckPullRest" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven


    - name: Clone Viktor3RDart/Ci-cd PUBLIC repository
    - uses: Viktor3RDart/Ci-cd@main
      with:
            owner: 'Viktor3RDart'
            repository: 'Ci-cd'
    - run: docker-compose up --build -d

#    - uses: browser-actions/setup-chrome@latest
#    - run: chrome --version
    
    - name: Run tests with Maven
      run: mvn -B clean test
